name: techarrow_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  carousel_slider: ^5.0.0
  desktop_drop: ^0.5.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  fluttertoast: ^8.2.11
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  material_symbols_icons: ^4.2805.1
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  window_size: ^0.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
